name: Update README Activity

on:
  workflow_dispatch:
  schedule:
  - cron: "0 * * * *"

permissions: write-all

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: jamesgeorge007/github-activity-readme@v0.4.1
      with:
        GH_USERNAME: kumartanmay-28
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
